### ISSUE TITLE
Duda temporizador

### ISSUE THREAD

**Issue by cruzIago** [Sr-fer/Ejercicios-S18-Refactorizados#2]
En temporizador.js, da el error "this.text_temporizador is undefined". En ningún momento está declarada la variable, por ello da el error

**Comment by Sr-fer** [comment]
Una vez definido cada vez que me da el tiempo este mismo no aparece, aparece también como undefined, para que este se vaya recargando cada segundo que necesitaría hacer?

**Comment by cruzIago** [comment]
El problema del temporizador es el mismo que en cronómetro. Cuando inicias un "interval" o "timeOut", quien lanza ese método es el objeto "window". Por lo que para poder utilizar las variables del objeto temporizador, necesitas envíar por parámetro el objeto al crear el "interval" o "timeout" y no usar "this". Tal cual en cronómetro.
